# Phase 3 — deployable NixOS example configuration.
#
# This is a clean, reproducible reference. The Phase-3-specific bits are
# the two `boot.initrd.*` lines marked PHASE 3 below. Everything else is
# the same NixOS configuration shape we used since Phase 2 — bootloader,
# networking, operator user, SSH, TPM access.
#
# To use this as a starting point:
#   1. Run a Phase-2 install to bring up a LUKS+TPM-capable VM. See
#      ../../phase-2-tpm-sealing/docs/phase-2.md for that.
#   2. Drop this file at /etc/nixos/configuration.nix on the target.
#      Edit the obvious values (hostName, user name, time zone).
#   3. `sudo nixos-rebuild switch` then `sudo reboot`.
#   4. After reboot, enroll the TPM slot — once per device:
#        sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7 /dev/vda2
#   5. Reboot again. The boot should be silent (no passphrase prompt).
#
# The hardware-configuration.nix that imports here is auto-generated by
# nixos-generate-config during install — it carries the LUKS device
# UUID, kernel modules, and filesystem mounts.

{ config, lib, pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ];

  # --- Bootloader: UEFI + systemd-boot + systemd-style initrd ---
  #
  # systemd-boot is the modern UEFI bootloader; NixOS manages every entry
  # declaratively. The systemd-style initrd (boot.initrd.systemd.enable)
  # is required for Phase 3 — it bundles systemd-cryptsetup with TPM 2.0
  # support so the initrd can talk to /dev/tpmrm0 during the unlock step.
  # Without it, the TPM is unreachable until after the disk is unlocked
  # (too late to help with the unlock).
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.systemd.enable = true;                                       # PHASE 3

  # --- LUKS auto-unlock via TPM ---
  #
  # `tpm2-device=auto` in crypttabExtraOpts tells systemd-cryptsetup,
  # at boot, to try the TPM2 token in the LUKS header first. If the TPM
  # releases the sealed secret (PCR policy matches), the disk unlocks
  # silently. If the TPM refuses, systemd-cryptsetup falls through to
  # the passphrase prompt — slot 0 is still the recovery path.
  #
  # The device name "cryptroot" matches the LUKS volume name used by
  # cryptsetup luksOpen during Phase 2 install, and matches the
  # boot.initrd.luks.devices."cryptroot".device line in the generated
  # hardware-configuration.nix.
  boot.initrd.luks.devices.cryptroot.crypttabExtraOpts =
    [ "tpm2-device=auto" ];                                                # PHASE 3

  # --- Networking: hostname + DHCP on the virtio NIC ---
  networking.hostName = "nixos-luks";
  networking.useDHCP = lib.mkDefault true;

  # --- Time zone (cosmetic; affects log timestamps only) ---
  time.timeZone = "Asia/Kolkata";

  # --- Operator user. Password set post-install via passwd. ---
  # `tss` group is required for /dev/tpmrm0 read/write access from
  # userspace tools like tpm2_pcrread.
  users.users.gagan = {
    isNormalUser = true;
    description = "Gagan";
    extraGroups = [ "wheel" "tss" ];
  };

  # --- SSH server ---
  # Password auth ON for the POC phases — tightened later.
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = true;
    settings.PermitRootLogin = "no";
  };

  # --- TPM 2.0: tss user/group, udev rules, tpm2-tools ---
  # security.tpm2.enable creates /dev/tpmrm0 and grants tss group access.
  # abrmd is disabled because we use the kernel resource manager directly
  # (cleaner: one fewer userspace daemon; no dbus dependency).
  security.tpm2.enable = true;
  security.tpm2.tssUser = "tss";
  security.tpm2.abrmd.enable = false;

  # --- Baseline diagnostic + TPM-management packages ---
  environment.systemPackages = with pkgs; [
    vim
    git
    curl
    htop
    tpm2-tools                              # tpm2_pcrread, tpm2_getrandom, etc.
    cryptsetup                              # for systemd-cryptenroll + luksDump
  ];

  # --- Do not change after first install ---
  system.stateVersion = "25.11";
}
